version: '3.4'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3035:3001"
    command: sh entrypoint.sh
    environment:
      RAILS_ENV: 'development'
      RACK_ENV: 'development'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432'
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache:cached
      - bundle_cache:/bundle:cached
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: '/root/log/.psql_history'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

volumes:
  postgres:
  rails_cache:
  bundle_cache:
